name: nedproject
description: A Flutter structure application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  meta: ^1.1.7
  equatable: ^0.5.1
  jaguar_retrofit: ^2.8.8
  jaguar_serializer: ^2.2.12
  jaguar_mimetype: ^1.0.1

  event_bus: ^1.1.0

  shared_preferences: 0.5.6

  intl: ^0.16.0
  bloc: ^2.0.0
  validations: ^0.8.5+1
  flutter_bloc: ^2.1.1
  connectivity: ^0.4.9

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  validations_generator: ^0.8.4
  jaguar_retrofit_gen: ^2.8.10
  jaguar_serializer_cli: ^2.2.8
  build_runner: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
